# Generated by Django 2.1.2 on 2022-08-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_mausoleos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mausoleos',
            new_name='Mausoleo',
        ),
    ]
